# Generated by Django 3.0.8 on 2020-09-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storage/account')),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=64)),
                ('dateOfBirth', models.DateField(verbose_name='Date Of Birth')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.TextField(max_length=256)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('pincode', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.PositiveIntegerField(default=0, verbose_name='Store Credit')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='api.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='storage/product')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=4096)),
                ('specifications', models.TextField(max_length=4096)),
                ('mrp', models.PositiveIntegerField()),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('category', models.CharField(choices=[('EARP', 'Earphones'), ('HEAD', 'Headphones'), ('LAPT', 'Laptops'), ('VIRT', 'VR Headsets')], db_index=True, max_length=4)),
                ('inStock', models.BooleanField(default=True, verbose_name='In Stock')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.CharField(max_length=12, verbose_name='Payment ID')),
                ('billing', models.TextField(max_length=256, verbose_name='Billing Address')),
                ('revenue', models.PositiveIntegerField(default=0)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='api.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(10, 'One'), (20, 'Two'), (30, 'Three'), (40, 'Four'), (50, 'Five')])),
                ('message', models.TextField(blank=True, max_length=512, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Seller'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('DEL', 'Delivered'), ('CNL', 'Cancelled')], db_index=True, default='PEN', max_length=3)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Address')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Customer'),
        ),
    ]
